import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { fileURLToPath } from "node:url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const jsZipSourcePath = fileURLToPath(
  new URL("./node_modules/jszip/lib/index.js", import.meta.url)
);
const lieShimPath = fileURLToPath(new URL("./src/shims/lie.cjs", import.meta.url));
const setImmediateShimPath = fileURLToPath(
  new URL("./src/shims/setimmediate.ts", import.meta.url)
);

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2020",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  plugins: [
    {
      name: "setimmediate-shim",
      setup(build) {
        build.onResolve({ filter: /^jszip$/ }, () => ({
          path: jsZipSourcePath
        }));
        build.onResolve({ filter: /^lie$/ }, () => ({
          path: lieShimPath
        }));
        build.onResolve({ filter: /^setimmediate$/ }, () => ({
          path: setImmediateShimPath
        }));
      }
    }
  ],
  outfile: "main.js",
  minify: prod,
  logLevel: "info"
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
